# Add configuration values here, as shown below.

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

GOOGLE_CLIENT_ID: ""
GOOGLE_CLIENT_SECRET: ""

Line_pay_channel_id: ''
Line_pay_channel_secret: ''
Line_pay_end_point: 'https://sandbox-api-pay.line.me'
